### ISSUE TITLE
Crash when joining world on 1.18.2

### ISSUE THREAD

**Issue by Lucaslah** [LambdAurora/LambdaMap#15]
When I join a server/world on 1.18.2 my game crashes, when I ran this on 1.18.1 it worked fine.
```
java.lang.IncompatibleClassChangeError: Found interface net.minecraft.class_5455, but class was expected
	at dev.lambdaurora.lambdamap.map.WorldMap.getBiomeRegistry(WorldMap.java:105)
	at dev.lambdaurora.lambdamap.map.MapChunk.readBiomesNbt(MapChunk.java:423)
	at dev.lambdaurora.lambdamap.map.MapChunk.fromNbt(MapChunk.java:419)
	at dev.lambdaurora.lambdamap.map.storage.MapRegionFile.loadChunk(MapRegionFile.java:148)
```

**Comment by LambdAurora** [comment]
Fixed with #16.
